rdr: Fix incorrect error checking after fread()
fread() returns size_t, which is unsigned. Don't check
for negative values to avoid warnings from Clang.

/home/shade/dev/tigervnc/common/rdr/FileInStream.cxx:74:13: error: comparison of unsigned expression < 0 is always false [-Werror,-Wtautological-compare]
      if (n < 0 || ferror(file))
          ~ ^ ~